name: Metrics B
on:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
